### ISSUE TITLE
Searching for phone numbers does no longer work... 

### ISSUE THREAD

**Issue by Gateway85** [37coins/37coins-web#56]
Searching for phone numbers is not working. 

e.g. +17078623737 which is a valid number in the staging system is not found.

**Comment by mahmed0715** [comment]
Get /api/gateway/admin/accounts responding with data(ok)
but with filter params it responding [](response code 200 with no data)
Need to find out why server response has been changed

**Comment by Gateway85** [comment]
Just tested with REST client. The following works for me: 

https://qa.37coins.com/api/gateway/admin/accounts/?page=6&size=500

**Comment by Gateway85** [comment]
Rest Request 
https://qa.37coins.com/api/gateway/admin/accounts/?filter=mobile=+491777422851


SEVERE: Servlet.service() for servlet [com._37coins.MessagingApp] in context with path [] threw exception [Filtered request failed.] with root cause
cz.jirutka.rsql.parser.TokenMgrError: Lexical error at line 1, column 8.  Encountered: " " (32), after : ""
	at cz.jirutka.rsql.parser.RSQLParserTokenManager.getNextToken(RSQLParserTokenManager.java:663)
	at cz.jirutka.rsql.parser.RSQLParser.jj_consume_token(RSQLParser.java:379)
	at cz.jirutka.rsql.parser.RSQLParser.argument(RSQLParser.java:280)
	at cz.jirutka.rsql.parser.RSQLParser.constraint(RSQLParser.java:184)
	at cz.jirutka.rsql.parser.RSQLParser.conjunction(RSQLParser.java:146)
	at cz.jirutka.rsql.parser.RSQLParser.disjunction(RSQLParser.java:117)
	at cz.jirutka.rsql.parser.RSQLParser.input(RSQLParser.java:102)
	at cz.jirutka.rsql.parser.RSQLParser.parse(RSQLParser.java:94)
	at org.restnucleus.filter.QueryFilter.doFilter(QueryFilter.java:49)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com._37coins.HttpsEnforcerFilter.doFilter(HttpsEnforcerFilter.java:37)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at org.restnucleus.filter.CorsFilter.doFilter(CorsFilter.java:53)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Gateway85** [comment]
Deletion works via using this: 
![uploads/9ee8c175-301d-4a13-a68e-5a7743ff1a83/Screen Shot 2015-04-14 at 10.38.12.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F9ee8c175-301d-4a13-a68e-5a7743ff1a83%2FScreen+Shot+2015-04-14+at+10.38.12.png)

**Comment by mahmed0715** [comment]
when using filter query param its not working...
like https://qa.37coins.com/api/gateway/admin/accounts?filter=mobile=17078623737

**Comment by mahmed0715** [comment]
still server responding with empty array. with the filter request.
did you check server?
